# Generated by Django 4.0.4 on 2022-06-16 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='resort',
            fields=[
                ('resort_id', models.CharField(max_length=90, primary_key=True, serialize=False)),
                ('resort_name', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=90)),
                ('photo', models.ImageField(upload_to='')),
                ('description', models.CharField(max_length=90)),
                ('owner', models.CharField(max_length=90)),
                ('contact', models.IntegerField()),
                ('status', models.CharField(max_length=90)),
            ],
            options={
                'db_table': 'resort',
            },
        ),
    ]
