# Generated by Django 4.0.4 on 2022-06-16 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_idgen2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='idgen2',
        ),
    ]
