# Generated by Django 4.0.4 on 2022-06-16 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_delete_idgen2'),
    ]

    operations = [
        migrations.AddField(
            model_name='idgen1',
            name='resort_id',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
    ]
