# Generated by Django 4.0.4 on 2022-06-16 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_idgen1_resort_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='homestay',
            fields=[
                ('homestay_id', models.CharField(max_length=90, primary_key=True, serialize=False)),
                ('photo', models.ImageField(upload_to='')),
                ('house_name', models.CharField(max_length=30)),
                ('roof', models.CharField(max_length=90)),
                ('description', models.CharField(max_length=90)),
                ('food', models.CharField(max_length=90)),
                ('owner', models.CharField(max_length=90)),
                ('contact', models.IntegerField()),
                ('status', models.CharField(max_length=90)),
            ],
            options={
                'db_table': 'homestay',
            },
        ),
        migrations.AddField(
            model_name='idgen1',
            name='homestay_id',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
    ]
