# Generated by Django 4.0.4 on 2022-06-21 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_homestay_idgen1_homestay_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='login',
            fields=[
                ('username', models.CharField(max_length=90, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=30)),
                ('category', models.CharField(max_length=90)),
            ],
            options={
                'db_table': 'login',
            },
        ),
    ]
