# Generated by Django 4.0.4 on 2022-06-27 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='traveller',
            fields=[
                ('traveller_id', models.CharField(max_length=90, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=90)),
                ('country', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('id_proof', models.ImageField(upload_to='')),
                ('contact', models.IntegerField()),
                ('email', models.CharField(max_length=90)),
            ],
            options={
                'db_table': 'traveller',
            },
        ),
    ]
