# Generated by Django 4.0.4 on 2022-06-27 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_traveller'),
    ]

    operations = [
        migrations.AddField(
            model_name='idgen1',
            name='traveller_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
