# Generated by Django 4.0.4 on 2022-06-27 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_idgen1_traveller_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='traveller',
            old_name='location',
            new_name='district',
        ),
    ]
