# Generated by Django 4.0.4 on 2022-06-27 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_rename_location_traveller_district'),
    ]

    operations = [
        migrations.RenameField(
            model_name='traveller',
            old_name='id_proof',
            new_name='photo',
        ),
    ]
