# Generated by Django 4.0.4 on 2022-06-28 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_homestaybooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='idgen1',
            name='homestaybooking_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
