# Generated by Django 4.0.4 on 2022-06-28 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_idgen1_homestaybooking_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='homestaybooking',
            new_name='homestaybooking1',
        ),
    ]
