# Generated by Django 4.0.4 on 2022-06-28 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_rename_homestaybooking_homestaybooking1'),
    ]

    operations = [
        migrations.AddField(
            model_name='idgen1',
            name='resortbooking_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='resortbooking1',
            fields=[
                ('resortbooking_id', models.CharField(max_length=90, primary_key=True, serialize=False)),
                ('booking_date', models.CharField(max_length=90)),
                ('no_of_days', models.CharField(max_length=30)),
                ('no_of_person', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=30)),
                ('resort_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.homestay')),
                ('traveller_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.traveller')),
            ],
            options={
                'db_table': 'resortbooking',
            },
        ),
    ]
