# Generated by Django 4.0.4 on 2022-06-28 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_idgen1_resortbooking_id_resortbooking1'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='homestaybooking1',
            table='homestaybooking1',
        ),
        migrations.AlterModelTable(
            name='resortbooking1',
            table='resortbooking1',
        ),
    ]
