# Generated by Django 4.0.4 on 2022-06-28 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0016_alter_homestaybooking1_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resortbooking1',
            name='resort_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.resort'),
        ),
    ]
