# Generated by Django 4.0.4 on 2022-06-28 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0017_alter_resortbooking1_resort_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='idgen1',
            name='activitybooking_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='activitybooking1',
            fields=[
                ('activitybooking_id', models.CharField(max_length=90, primary_key=True, serialize=False)),
                ('booking_date', models.CharField(max_length=90)),
                ('no_of_days', models.CharField(max_length=30)),
                ('no_of_person', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=30)),
                ('activity_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.activity')),
                ('traveller_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.traveller')),
            ],
            options={
                'db_table': 'activitybooking1',
            },
        ),
    ]
