# Generated by Django 4.0.4 on 2022-06-30 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0018_idgen1_activitybooking_id_activitybooking1'),
    ]

    operations = [
        migrations.AddField(
            model_name='idgen1',
            name='act_review_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='idgen1',
            name='hom_review_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='idgen1',
            name='res_review_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='resortreview',
            fields=[
                ('res_review_id', models.CharField(max_length=90, primary_key=True, serialize=False)),
                ('review', models.CharField(max_length=150)),
                ('review_date', models.CharField(max_length=90)),
                ('resort_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.resort')),
                ('traveller_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.traveller')),
            ],
            options={
                'db_table': 'resortreview',
            },
        ),
        migrations.CreateModel(
            name='homestayreview',
            fields=[
                ('hom_review_id', models.CharField(max_length=90, primary_key=True, serialize=False)),
                ('review', models.CharField(max_length=150)),
                ('review_date', models.CharField(max_length=90)),
                ('homestay_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.homestay')),
                ('traveller_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.traveller')),
            ],
            options={
                'db_table': 'homestayreview',
            },
        ),
        migrations.CreateModel(
            name='activityreview',
            fields=[
                ('act_review_id', models.CharField(max_length=90, primary_key=True, serialize=False)),
                ('review', models.CharField(max_length=150)),
                ('review_date', models.CharField(max_length=90)),
                ('activity_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.activity')),
                ('traveller_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.traveller')),
            ],
            options={
                'db_table': 'activityreview',
            },
        ),
    ]
