# Generated by Django 4.0.4 on 2022-07-01 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0019_idgen1_act_review_id_idgen1_hom_review_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homestay',
            name='rate',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resort',
            name='rate',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
