# Generated by Django 4.0.4 on 2022-07-01 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0020_homestay_rate_resort_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homestay',
            name='rate',
            field=models.CharField(max_length=90),
        ),
        migrations.AlterField(
            model_name='resort',
            name='rate',
            field=models.CharField(max_length=90),
        ),
    ]
