# Generated by Django 4.0.4 on 2022-07-01 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0021_alter_homestay_rate_alter_resort_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homestay',
            name='contact',
            field=models.CharField(max_length=90),
        ),
        migrations.AlterField(
            model_name='resort',
            name='contact',
            field=models.CharField(max_length=90),
        ),
    ]
